import type { Metadata } from "next";
import "./globals.css";
import StoreWrapper from "@/store/store";
import Navbar from "@/components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <StoreWrapper>{children}</StoreWrapper>
      </body>
    </html>
  );
}
